Extracted method that 'detects push method by reg id'
appfeel/node-pushnotifications pull request #149
Opened 2021-01-17 21:28 UTC by jkblume

Extracted method that detects device type / used push method out of send method. I will use it for logging / persisting the device type that was used by send() method.

2021-01-24 22:39 UTC, alex-friedl requested changes

2021-01-24 22:39 UTC, alex-friedl commented on src/push-notifications.js
> +      const pushMetdod = this.getPushMethodByRegId(regId);
typo `pushMethod`

2021-01-24 22:39 UTC, alex-friedl commented on src/push-notifications.js
> +  getPushMethodByRegId(regId) {
please add test in `test/push-notifications/basic.js`

2021-01-24 22:39 UTC, alex-friedl commented on src/push-notifications.js
> +  getPushMethodByRegId(regId) {
please add documentation about newly exported function in `README.md`

2021-04-19 11:09 UTC, jkblume commented
Thanks for your review and sorry for my late response. I tried to address your points and hope it matches your expectations. I am glad to hear from you.

2021-04-24 15:07 UTC, alex-friedl approved these changes

2021-04-24 15:08 UTC, merged