Deprecated FCM APIs, add FCM method (HTTP v1 new API)
appfeel/node-pushnotifications pull request #194
Opened 2023-09-18 11:13 UTC by banshiAnton

2024-01-02 23:09 UTC, infuzz commented
HI !
Any plan to merge this great PR in the base repo ?

2024-01-03 11:52 UTC, miqmago commented
@banshiAnton first of all sorry for the delay on the review and many thanks for your contribution. I think it can help to evolve the repo to better integration with FCM/GCM.

I've made some comments on your code that would help to make this repo better mantainable.

If possible, could you please add the corresponding documentation for the new options to the Readme.md, and perhaps include the examples from this pull request? It would be really helpful!

2024-01-10 14:01 UTC, banshiAnton commented
Hi @miqmago i have updated README.md
but i can't see any comments for code

`I've made some comments on your code that would help to make this repo better mantainable.`

2024-01-10 17:38 UTC, miqmago commented
Hi @banshiAnton it's quite strange you can't see my comments... Don't appear to you on this thread? I can se them just few messages before this one, as a review... Also if you open https://github.com/appfeel/node-pushnotifications/pull/194/files?diff=split&w=1 I can see my comments there.

I've added a ping on one of them to see if you receive a message on the first one. Just let me know if it works, I will ping on every comment then.

2024-01-10 17:39 UTC, miqmago requested changes

2024-01-10 17:39 UTC, miqmago commented on src/push-notifications.js
> +      const pushMethod = this.settings.useFCMMethodInsteadOfGCM
@banshiAnton

2024-01-10 17:40 UTC, miqmago commented
Ok @banshiAnton I've just noticed that I had to submit my review... You should see it now.

2024-01-10 20:28 UTC, alex-friedl commented on src/utils/tools.js
> +  R.is.bind(null, String),
I don't see any scenario where using `.bind()` on a ramda function makes sense to be honest?
@banshiAnton Could you explain what you are trying to do here?

2024-01-11 14:41 UTC, banshiAnton commented on src/push-notifications.js
> +      const pushMethod = this.settings.useFCMMethodInsteadOfGCM
probable we should set `isLegacyGCM: true` by default for backward compatibility
or not ?

2024-01-11 15:58 UTC, miqmago commented on src/push-notifications.js
> +      const pushMethod = this.settings.useFCMMethodInsteadOfGCM
Yes, I think it makes sense to create a major as we are on the way to replace a deprecated API, so for me it makes sense to release a new version with isLegacyGCM: false.

This way we can migrate and make it backward compatible, but by default use the new api.

Maybe @alex-friedl has different point of view or not?

2024-01-11 18:50 UTC, alex-friedl commented on src/push-notifications.js
> +      const pushMethod = this.settings.useFCMMethodInsteadOfGCM
I agree, releasing a new major version that uses FCM by default makes sense.
We could consider to release a final 2.x version first, where GCM is still the default and then release 3.0.0 with FCM being the default?

2024-01-11 18:51 UTC, alex-friedl commented on src/utils/tools.js
> +  R.is.bind(null, String),
Yes, all ramda functions are curried by default :) 
But regarding the function itself, why the check for the string? Are there are any cases where you want to return non-String inputs unchanged?

2024-01-12 16:51 UTC, banshiAnton commented on src/utils/tools.js
> +  R.is.bind(null, String),
this is for `titleLocArgs` and `locArgs` [iOS alert](https://github.com/appfeel/node-pushnotifications/blob/master/src/sendAPN.js#L25)
args should be json stringify array
```js
{
...
titleLocArgs: '["Smith", "M"]'
}
```
i think this is strange why i can't pass just like simple array `['Smith', 'M']` w/o `JSON.stringify`
so for backward compatibility i try to `JSON.parse` only for `String` type

2024-01-12 21:01 UTC, alex-friedl commented on src/utils/tools.js
> +  R.is.bind(null, String),
I see. It's been a while but if I read through https://github.com/appfeel/node-pushnotifications/issues/150 I think you could simply stick with the previous implementation and only call `alertLocArgsToJSON()` for APN messages? Or what's the reason behind also calling `toJsonOrUndefined` when constructing the GSM message?

2024-03-04 16:12 UTC, vcarballo commented on README.md
> +    frined_id: 54657,
Is this supposed to be friend_id?

2024-03-15 00:37 UTC, infuzz commented
Hello, I just want to thank you for all your great work, as the deprecation of the old http fcm is fast approaching. I hope you have enough time to finish the new major version. Thanks again.

2024-03-24 22:19 UTC, miqmago commented
From my side seems all fine.
@alex-friedl could you please confirm if is it ok for you?
@banshiAnton could you please solve package conflicts?

2024-04-03 20:14 UTC, alex-friedl commented
@miqmago @banshiAnton Generally looks good to me as well. 
@banshiAnton When you get to rebasing the branch, could you also take a look at the open conversations in the PR? :)

2024-04-08 21:49 UTC, Hossman333 commented
Thanks everyone for your great work here! This will be good to have so that we aren't left in a broken state in June.

2024-04-18 20:20 UTC, nsakaimbo commented
@banshiAnton Nice work! I believe you're missing an export reference in the file `lib/push_notifications.js`. It currently looks like:

```
module.exports = PN;
module.exports.WEB = _constants.WEB_METHOD;
module.exports.WNS = _constants.WNS_METHOD;
module.exports.ADM = _constants.ADM_METHOD;
module.exports.GCM = _constants.GCM_METHOD;
module.exports.APN = _constants.APN_METHOD;
```

You will need to add `module.exports.FCM` there as well.

2024-04-27 11:16 UTC, miqmago commented
@banshiAnton are you available to make pull from master, resolve conflicts and push again to your branch? This would help with merging this important feature.

2024-05-01 17:01 UTC, nsakaimbo commented
@miqmago 👋🏽 I left a couple of comments with some important bug fixes for this PR. My review comment is still marked as "pending" so unsure if @banshiAnton is able to see it. Specifically:

- `module.exports.FCM = _constants.FCM_METHOD` needs to be added to the bottom of `lib/push_notifications.js`, and
- The TTL reference in `src/utils/fcmMessage.js` needs to be fixed so it reads `androidMessage.ttl = androidMessage.timeToLive` (i.e. `timeToLive` should not be snake-cased here). In addition, the ` *  1000` multiplier could cause issues as this value is already set in seconds, not ms.

2024-05-10 02:08 UTC, ehaynes99 commented
In [the linked issue in node-gcm](https://github.com/ToothlessGear/node-gcm/issues/370), the OP assumes that since it was deprecated on June 20, 2023, it will be discontinued on June 20, 2024, but [Google doesn't actually give a day](https://firebase.google.com/docs/cloud-messaging/migrate-v1?hl=en), only a month. It could as easily be June 1, so we're 3 weeks away.

Since we haven't heard from @banshiAnton since January, I forked the fork, updated it with current `master`, and addressed the feedback by @nsakaimbo 

I have opened a PR here: https://github.com/appfeel/node-pushnotifications/pull/205

Just to be clear, I'm not trying to steal credit in any way, and I don't pretend to have much domain knowledge nor a full grasp of all of the preceding changes. But my company depends on this library and will be in serious trouble without the update.

2024-05-20 15:50 UTC, pushchris commented
Deadline is fast approaching on this. When is this going to be merged and is there anything the rest of us can do to help expedite?

2024-05-28 08:51 UTC, Arpanexe commented
Any plan to merge this PR?

2024-06-03 09:49 UTC, NicolasBonduel commented
It looks like Google has updated their documentation, and now says the API will stop working on the 21st of June.

2024-06-05 02:38 UTC, ehaynes99 commented
FWIW, here's a general example of what I ended up with using `firebase-admin` directly. I closed my copy of this PR because it wasn't working correctly, and it was too painful trying to reverse engineer all of the transformations in here to map to the firebase syntax.
```typescript
import type firebase from 'firebase-admin'
import type { FirebaseError } from 'firebase-admin'
import type { TokenMessage } from 'firebase-admin/lib/messaging/messaging-api'

// 4 weeks - the maximum
const DEFAULT_TTL = 4 * 7 * 25 * 60

export type MyCustomPushNotification = {
  title: string
  body: string
  collapseKey?: string
  priority?: 'high' | 'normal'
  // any other properties
  data: Record<string, unknown>
}

export type FcmClient = {
  sendAndroid: (token: string, notification: MyCustomPushNotification) => Promise<void>
}

export const FcmClient = (firebaseApp: firebase.app.App): FcmClient => {
  return {
    sendAndroid: async (token, notification) => {
      const { collapseKey, priority = 'high' } = notification

      // Types: https://github.com/firebase/firebase-admin-node/blob/4070f5bf41f83368ec8f7c4f3136a25dfcdf3e03/src/messaging/messaging-api.ts#L20-L27
      const message: TokenMessage = {
        token,
        // see https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages
        // in short, you can have either or both of:
        // `data` can only be handled by the client app
        data: serializeData({
          title: notification.title,
          body: notification.body,
          ...notification.data,
          // any other properties
        }),
        // `notification` will be displayed by the phone OS unless the app is in focus
        notification: {
          title: notification.title,
          body: notification.body,
        },
        // you can send to multiple platforms. see: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
        // I only used android here like so:
        android: {
          collapseKey,
          priority,
          ttl: DEFAULT_TTL,
        },
        // the formats for other types are different, see the link above
        // apns: {
        //
        // },
        // webpush: {
        //
        // },
      }
      try {
        await firebaseApp.messaging().send(message)
      } catch (error) {
        console.error('FCM error:', { error, message })
        if (isFirebaseAuthErrorError(error)) {
          // invalidate the token in your app
        } else {
          throw error
        }
      }
    },
  }
}

const isFirebaseAuthErrorError = (error: unknown): error is FirebaseError => {
  return error instanceof Error && 'code' in error && error.code === 'messaging/registration-token-not-registered'
}

/**
 * `data` type for FCM must be a `Record<string, string>`. You can handle this however you like, but the way
 * we're doing it here is to to serialize any values that are not strings as JSON. The client will need
 * to parse these values back into objects.
 * Values that are already strings are left as is to avoid double encoding.
 */
const serializeData = (data: Record<string, unknown>): Record<string, string> => {
  return Object.fromEntries(
    Object.entries(data).map(([key, value]) => [key, typeof value === 'string' ? value : JSON.stringify(value)]),
  )
}
```

2024-06-18 01:16 UTC, wcalebgray commented
I copied over the code from this PR to my fork and got all of the test cases passing. I'll be trying to get this to work tomorrow, but any help would be appreciated. Maybe we can still get this merged and updated before Friday.

2024-06-19 20:22 UTC, alex-friedl commented
Superseded by https://github.com/appfeel/node-pushnotifications/pull/207

2024-06-19 20:22 UTC, closed without merging